name: Build LEDE

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 3 * *'
permissions: 
  contents: write
env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_NAME: lede
  WORKDIR: /mnt/lede
  CCACHE_DIR: /mnt/ccache_lede
  CCACHE_MAXSIZE: 10G

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Free disk space
        run: |
          #df -h
          chmod +x $GITHUB_WORKSPACE/scripts/cleanup.sh
          chmod +x $GITHUB_WORKSPACE/scripts/free-disk-space.sh
          #sudo bash $GITHUB_WORKSPACE/scripts/cleanup.sh
          sudo bash $GITHUB_WORKSPACE/scripts/free-disk-space.sh       #Use with caution, as it may damage the environment.

      - name: Prepare system
        run: |
          sudo -E timedatectl set-timezone "Asia/Shanghai"
          date
          sudo apt update
          sudo apt install -y bc lm-sensors pciutils wsdd2 
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext \
          genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev \
          libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev \
          libreadline-dev libssl-dev libtool llvm lrzsz libnsl-dev ninja-build p7zip p7zip-full patch pkgconf \
          python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion \
          swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

      - name: Prepare workspace
        run: |
          sudo mkdir -p /mnt
          sudo chown $USER:$USER /mnt

      - name: Clone source
        run: |
          git clone --depth=1 $REPO_URL $WORKDIR

      - name: Run first script (add packages)
        run: |
          cd $WORKDIR
          FILE=$(ls $GITHUB_WORKSPACE/lede/lede*.sh | sed -n '1p')
          chmod +x "$FILE"
          "$FILE"

      - name: Feeds update
        run: |
          cd $WORKDIR
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy config
        run: |
          mv $GITHUB_WORKSPACE/lede/.config $WORKDIR/.config   

      - name: Run second script
        run: |
          cd $WORKDIR
          FILE=$(ls $GITHUB_WORKSPACE/lede/lede*.sh | sed -n '2p')
          chmod +x "$FILE"
          "$FILE"

      - name: download
        run: |
          cd $WORKDIR
          make download -j8

      - name: Prepare config
        run: |
          cd $WORKDIR
          make clean
          make defconfig 
          #chmod +x $GITHUB_WORKSPACE/check-packages-status.sh
          #bash $GITHUB_WORKSPACE/check-packages-status.sh
          #chmod +x $GITHUB_WORKSPACE/auto-fix-packages.sh
          #
          ##### Remove commentâ€‘restore function #####
          #bash $GITHUB_WORKSPACE/auto-fix-packages.sh
          #
          chmod +x $GITHUB_WORKSPACE/check-packages.sh
          bash $GITHUB_WORKSPACE/check-packages.sh

      - name: Compile
        run: |
          cd $WORKDIR
          export PATH="/usr/lib/ccache:$PATH"
          export CCACHE_DIR=$CCACHE_DIR
          ccache -M $CCACHE_MAXSIZE
          make -j$(nproc) || make -j1

      - name: Detect platform
        run: |
          cd $WORKDIR
          FILE=$(find bin/targets -name "openwrt-*.manifest" ! -name "Packages.manifest" | head -n 1)

          if [ -z "$FILE" ]; then
            echo "No manifest found!"
            exit 1
          fi

          BASE=$(basename "$FILE")
          ARCH=$(echo "$BASE" | cut -d'-' -f2)
          SUBTARGET=$(echo "$BASE" | cut -d'-' -f3)
          DEVICE=$(echo "$BASE" | sed -E 's/^openwrt-[^-]+-[^-]+-(.+)\.manifest/\1/')
          DATE=$(date +"%Y%m%d-%H%M")

          ZIP="lede-${ARCH}-${SUBTARGET}-${DEVICE}-${DATE}.zip"
          TAG="lede-${ARCH}-${SUBTARGET}-${DATE}"

          echo "ZIP=$ZIP" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "ARCH=$ARCH" >> $GITHUB_ENV
          echo "SUBTARGET=$SUBTARGET" >> $GITHUB_ENV
          echo "DEVICE=$DEVICE" >> $GITHUB_ENV

      - name: Package
        run: |
          cd $WORKDIR
          mkdir -p output
          find bin/targets -type f \
            ! -path "*/packages/*" \
            ! -name "*buildinfo" \
            ! -name "profiles.json" \
            ! -name "version.buildinfo" \
            ! -name "config.buildinfo" \
            ! -name "feeds.buildinfo" \
            | zip -j "$ZIP" -@
          mv "$ZIP" output/

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP }}
          path: ${{ env.WORKDIR }}/output/${{ env.ZIP }}

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: ${{ env.WORKDIR }}/output/${{ env.ZIP }}
          body: |
            ## Device Platform Information

            Architecture: ${{ env.ARCH }}
            Subtarget:    ${{ env.SUBTARGET }}
            Device:       ${{ env.DEVICE }}

            Build Tag:    ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
